# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'
dpr_wiki_10k:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /data/tuyen/openqa/DPR/downloads/data/wikipedia_split/psgs_w100_10k.tsv
  id_prefix: 'wiki:'
